# Generates a C++ source with the contents of selected bin/resources files baked in.
#
# The libretro core is a single file dropped into someone else's frontend, and
# the builds people install ship the core alone - the shaders are expected to be
# found in a resources directory the user assembles by hand. They drift apart
# whenever a shader changes, and the failure is a shader that will not compile,
# which reads like a driver fault. Building them into the core removes the class
# of problem for the one part of resources that stops it booting.
#
# Run in script mode:
#   cmake -DRESOURCES_DIR=<dir> -DOUTPUT_CPP=<file> -P EmbedResources.cmake

if(NOT DEFINED RESOURCES_DIR OR NOT DEFINED OUTPUT_CPP)
	message(FATAL_ERROR "RESOURCES_DIR and OUTPUT_CPP must be set")
endif()

# The shaders, plus the three fonts ImGuiManager::LoadFontData() treats as fatal
# when missing. Everything else in resources only costs the feature that wants it.
file(GLOB_RECURSE shader_files RELATIVE "${RESOURCES_DIR}" "${RESOURCES_DIR}/shaders/*")
set(font_files
	"fonts/Roboto-Regular.ttf"
	"fonts/RobotoMono-Medium.ttf"
	"fonts/fa-solid-900.ttf"
	"fonts/promptfont.otf")
# GameIndex.yaml is not needed to boot, but without it every game runs without
# its fixes, which reads as "the core is broken on this game" rather than as a
# missing optional file - and on Android the resources directory is awkward or
# impossible to populate. It is the one large resource worth the binary size.
set(database_files
	"GameIndex.yaml")
set(shader_files ${shader_files} ${font_files} ${database_files})
list(SORT shader_files)
list(LENGTH shader_files shader_count)
if(shader_count EQUAL 0)
	message(FATAL_ERROR "No resources found under ${RESOURCES_DIR}")
endif()
foreach(needed ${font_files} ${database_files})
	if(NOT EXISTS "${RESOURCES_DIR}/${needed}")
		message(FATAL_ERROR "${needed} is missing from ${RESOURCES_DIR}")
	endif()
endforeach()

set(blobs "")
set(table "")
set(index 0)
foreach(shader ${shader_files})
	file(READ "${RESOURCES_DIR}/${shader}" hex HEX)
	# One byte array rather than a string literal: ffx_a.h alone is 161 KB and
	# MSVC caps a string literal at 65535 bytes.
	string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
	string(LENGTH "${hex}" hex_length)
	math(EXPR byte_length "${hex_length} / 2")

	string(APPEND blobs "static const unsigned char s_resource_${index}[] = {${bytes}};\n\n")
	string(APPEND table "\t{\"${shader}\", reinterpret_cast<const char*>(s_resource_${index}), ${byte_length}},\n")
	math(EXPR index "${index} + 1")
endforeach()

set(generated "// Generated by cmake/EmbedShaders.cmake - do not edit.\n\n")
string(APPEND generated "#include \"EmbeddedResources.h\"\n\n")
string(APPEND generated "namespace\n{\n${blobs}")
string(APPEND generated "struct EmbeddedResource\n{\n\tconst char* name;\n\tconst char* data;\n\tunsigned int size;\n};\n\n")
string(APPEND generated "const EmbeddedResource s_embedded_resources[] = {\n${table}};\n} // namespace\n\n")
string(APPEND generated "std::optional<std::string_view> GetEmbeddedResource(const std::string_view name)\n{\n")
string(APPEND generated "\tfor (const EmbeddedResource& resource : s_embedded_resources)\n\t{\n")
string(APPEND generated "\t\tif (name == resource.name)\n\t\t\treturn std::string_view(resource.data, resource.size);\n\t}\n\n")
string(APPEND generated "\treturn std::nullopt;\n}\n")

# Only rewrite when the contents change, so a rebuild does not cascade.
if(EXISTS "${OUTPUT_CPP}")
	file(READ "${OUTPUT_CPP}" existing)
	if(existing STREQUAL generated)
		return()
	endif()
endif()
file(WRITE "${OUTPUT_CPP}" "${generated}")
message(STATUS "Embedded ${shader_count} resources into ${OUTPUT_CPP}")
